version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    tty: true
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
      TZ: Asia/Tokyo
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - workspace:/workspace
    working_dir: /workspace
    ports:
      - '3000:3000'
volumes:
  vscode-extensions:
  workspace:
